version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: bumacard-mysql
    restart: always
    environment:
      MYSQL_DATABASE: bumacard
      MYSQL_USER: bumacard
      MYSQL_PASSWORD: bumacard
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

volumes:
  db_data:
